# TownyPolitics Configuration

# Political Power Settings
political_power:
  # The maximum daily political power gain for any nation
  max_daily_gain: 5.0

  # The minimum daily political power gain for any nation with at least one resident
  min_daily_gain: 1.0

  # The cost of various diplomatic actions (will be implemented in future updates)
  costs:
    ally: 10.0
    enemy: 5.0
    neutral: 2.0

# Government Settings
government:
  # Cooldown between government changes (in days)
  change_cooldown: 30

  # Time it takes to switch governments after the first switch (in days)
  switch_time: 7

# Update this section in your config.yml

# Corruption Settings
corruption:
  # Base daily corruption gain for all nations
  base_daily_gain: 0.5

  # Corruption thresholds (%)
  thresholds:
    low: 25.0       # Low corruption threshold
    medium: 50.0    # Medium corruption threshold
    high: 75.0      # High corruption threshold
    critical: 90.0  # Critical corruption threshold

  # Embezzlement rates for tax income (% of taxes embezzled)
  embezzlement:
    low: 0.05        # 5% of tax revenue lost
    medium: 0.15     # 15% of tax revenue lost
    high: 0.30       # 30% of tax revenue lost
    critical: 0.60   # 60% of tax revenue lost

  # Tax collection notifications
  notifications:
    embezzlement_message: true  # Show embezzlement messages in nation chat

  # Effects of corruption thresholds
  effects:
    # Taxation modifier effects by threshold (values are multiplication factors)
    taxation:
      low: 1.05      # +5% max taxation
      medium: 1.10   # +10% max taxation
      high: 1.15     # +15% max taxation
      critical: 1.20 # +20% max taxation

    # Political Power modifiers by threshold
    political_power:
      low: 1.0       # No effect
      medium: 0.9    # -10% PP gain
      high: 0.75     # -25% PP gain
      critical: 0.5  # -50% PP gain

    # Resource output modifiers by threshold
    resources:
      low: 0.95      # -5% resource output
      medium: 0.85   # -15% resource output
      high: 0.75     # -25% resource output
      critical: 0.6  # -40% resource output

    # Spending modifiers by threshold
    spending:
      low: 1.1       # +10% spending costs
      medium: 1.2    # +20% spending costs
      high: 1.3      # +30% spending costs
      critical: 1.5  # +50% spending costs

  # Political power penalties by threshold
  power_penalties:
    high: 0.025      # 2.5% daily political power loss
    critical: 0.05   # 5% daily political power loss

  # Future security spending levels (to be implemented)
  security_spending:
    level_1:
      cost: 5.0
      reduction: 20.0
    level_2:
      cost: 10.0
      reduction: 40.0
    level_3:
      cost: 20.0
      reduction: 70.0