# TownyPolitics Configuration

# Debug Settings
debug:
  enabled: false
  log_to_file: true
  file_name: "debug.log"
  log_level: INFO

# Political Power Settings
political_power:
  max_daily_gain: 5.0
  min_daily_gain: 1.0

# Government Settings
government:
  change_cooldown: 30
  switch_time: 7

# Corruption Settings
corruption:
  base_daily_gain: 0.5
  thresholds:
    low: 25.0
    medium: 50.0
    high: 75.0
    critical: 90.0
  embezzlement:
    low: 0.05
    medium: 0.15
    high: 0.30
    critical: 0.60
  notifications:
    embezzlement_message: true
  effects:
    taxation:
      low: 1.05
      medium: 1.10
      high: 1.15
      critical: 1.20
    political_power:
      low: 1.0
      medium: 0.9
      high: 0.75
      critical: 0.5
    resources:
      low: 0.95
      medium: 0.85
      high: 0.75
      critical: 0.6
    spending:
      low: 1.1
      medium: 1.2
      high: 1.3
      critical: 1.5
  power_penalties:
    high: 0.025
    critical: 0.05

# Town Corruption Settings
town_corruption:
  base_daily_gain: 0.4
  thresholds:
    low: 25.0
    medium: 50.0
    high: 75.0
    critical: 90.0
  effects:
    taxation:
      low: 0.95
      medium: 0.90
      high: 0.80
      critical: 0.70
    trade:
      low: 0.95
      medium: 0.90
      high: 0.80
      critical: 0.70

# Town Government Settings
town_government:
  change_cooldown: 15

# Town Political Power Settings
town_political_power:
  base_gain: 0.8
  max_daily_gain: 4.0
  min_daily_gain: 0.8
  nation_bonus: 0.1

# Database Settings
database:
  host: localhost
  port: 3306
  database: townypolitics
  username: root
  password: password
  prefix: tp_
  connection_pool_size: 10
  max_lifetime: 1800000